mod 'inifile',  '2.0.0',   :github_tarball => 'puppetlabs/puppetlabs-inifile'
mod 'boxen',    '3.13.0c', :github_tarball => 'n0ts/puppet-boxen'
mod 'homebrew', '2.1.0f',  :github_tarball => 'n0ts/puppet-homebrew'
mod 'stdlib',   '4.17.1',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
